variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - install

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - mvn clean compile -B

unit-test-job:   # This job runs in the test stage.
  stage: test
  script:
    - mvn verify -B

deploy-job:      # This job runs in the deploy stage.
  stage: install
  script:
    - mvn deploy -DskipTests