name: Deploy LogicNG to the Maven Package Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.SONATYPE_GPG_PRIVATE_KEY }}
          gpg-passphrase: SONATYPE_GPG_PRIVATE_KEY_PASSPHRASE
      - name: Build with Maven
        run: mvn -ntp deploy -DskipTests -P gh-action-release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PRIVATE_KEY_PASSPHRASE }}
