name: Build and Test LogicNG on different Operating Systems

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: The version tag to be used

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - name: Build with Maven
        run: mvn -ntp package
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and Push Image
        run: |
          docker build . -t ghcr.io/booleworks/boolerules:${{inputs.version}}-x64
          docker push ghcr.io/booleworks/boolerules:${{inputs.version}}-x64
